### ISSUE TITLE
'libssh2_sftp_read.vi' reads incomplete data if the buffer contains null characters.

### ISSUE THREAD

**Issue by sanch3z** [logmanoriginal/lvssh2#4]
Hi,

when you read a binary file via SFTP, then chunks that contain the null character are incomplete.

Is this possibly due to how LabVIEW converts C strings to LV strings?

Best regards
sanch3z

**Comment by logmanoriginal** [comment]
Good catch, thanks for the report.

**Comment by logmanoriginal** [comment]
This issue is fixed in the main branch. Thanks again for your support!
