### ISSUE TITLE
Error 5042 when using libssh2_channel_shell.vi.

### ISSUE THREAD

**Issue by sanch3z** [logmanoriginal/lvssh2#9]
Hi

whenever I try to open a shell with `libssh2_channel_shell.vi` I get error 5042. `libssh2_session_last_error.vi` converts this to `error -43, Failed waiting for channel success`.

I'm not sure if this is necessary but i do request a PTY via `libssh2_channel_request_pty.vi`.

When this happens, the server reports the following message:
```session_shell_req: parse packet: Connection from user <user> <ip> port <port>: unexpected bytes remain after decoding```

I looked at example C code and tried to port that to LabVIEW using this library. Am I missing something obvious that needs to be done in LabVIEW to make this work?

**Comment by logmanoriginal** [comment]
This looks like an issue in the transport layer between libssh2 and your server. In principle, this should work out of the box. Without the code it is difficult to say why it fails.

Please try the channel_request_pty example included with the library. It is based on the example from libssh2 and available from the example finder when using the directory view:

![image](https://github.com/user-attachments/assets/7cc51bc4-87f7-4173-8408-dd5ca9479049)

**Comment by sanch3z** [comment]
I adapted the vi so that it requests a process of type `shell` instead of `exec`. 

`libssh2_channel_shell.vi` returns the error mentioned before.

![image](https://github.com/user-attachments/assets/cc28767f-a1f7-429b-870e-f0c2f9b0db39)

**Comment by logmanoriginal** [comment]
Good catch.

Took me a while to figure out what is wrong here. Turns out that `libssh2_channel_process_startup` only checks if `message` is defined and not whether `message_len` is greater than zero: https://github.com/libssh2/libssh2/blob/e2b2c026869f9c8b9d1881729007fb95007ef0fa/src/channel.c#L1568-L1569
```
        if(message)
            _libssh2_store_u32(&s, (uint32_t)message_len);
```

These are the extra bytes that cause the error. The fix is to provide NULL for `message` when `message_len` is zero. Fix incoming...

**Comment by logmanoriginal** [comment]
The fix is included in the latest release: https://github.com/logmanoriginal/lvssh2/releases/tag/0.3.0

Let me know if this fixes your issue.

**Comment by sanch3z** [comment]
This, indeed, fixes my issue, tysm.

Is there any way I can support your work?

**Comment by logmanoriginal** [comment]
Awesome, thanks for the feedback!

As for support, please don't hesitate to report further bugs an issues you may discover. I'm pretty confident in the stability of this library but sometimes there are strange behaviors like the one you discovered here.

Thanks again for reporting this issue :)
